apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-aspnet-core
  name: hello-aspnet-core
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-aspnet-core
  sessionAffinity: None
  type: NodePort
